__include__: [
  '../dfine/dfine_hgnetv2_s_custom.yml',
  '../base/deim.yml'
]

print_freq: 20
output_dir: ./outputs/deim_hgnetv2_s_custom

DEIM:
  backbone: HGNetv2_LightMB_CA_iRMB_DualAtt

HGNetv2_LightMB_CA_iRMB_DualAtt:
  name: 'B0'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True
  pretrained: False

HybridEncoder:
  in_channels: [128, 256, 512]

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*(bn|norm)).*$'
      lr: 0.0002
    - 
      params: '^(?=.*(?:norm|bn)).*$'     # except bias
      weight_decay: 0.

  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epoches: 132
flat_epoch: 64
no_aug_epoch: 12

train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [4, 64, 120]

  collate_fn:
    mixup_epochs: [4, 64]
    stop_epoch: 120
  total_batch_size: 4

val_dataloader:
  total_batch_size: 4
